# Generated by Django 4.1.7 on 2023-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0002_rename_created_at_user_date_joined_alter_user_avatar_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="비밀번호"),
        ),
    ]
