# Generated by Django 4.1.7 on 2023-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_user_nick_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="account/avatar/%Y/%m/%d", verbose_name="아바타"
            ),
        ),
    ]
