# Generated by Django 4.1.7 on 2023-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nick_name",
            field=models.CharField(max_length=150, unique=True, verbose_name="닉네임"),
        ),
    ]
