# Generated by Django 4.1.7 on 2023-03-16 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_post_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.CharField(max_length=1000, verbose_name="태그"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=1000, verbose_name="내용"),
        ),
    ]
