# Generated by Django 4.1.7 on 2023-03-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boom", "0002_alter_post_author_alter_post_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
    ]
