# Generated by Django 4.1.7 on 2023-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0003_alter_comment_author_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="instagram/post/%Y/%m/%d"),
        ),
    ]
