# Generated by Django 4.1.7 on 2023-03-28 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0005_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
