# Generated by Django 4.1.7 on 2023-03-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boom", "0008_alter_post_ocr_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="similar_post_set",
            field=models.ManyToManyField(blank=True, to="boom.post"),
        ),
    ]
